### ISSUE TITLE
Recent Review Feature Requests List

### ISSUE THREAD

**Issue by turtlemaster19** [davidsansome/tsurukame#189]
Checklist of recent review feature requests:
- [ ] #172: Only show part that was incorrect
- [ ] #174: Reverse-search incorrect answer
- [ ] #178: All meanings, then all reading sort
- [ ] #183: Show hints in reviews
- [ ] #187: Don't allow Japanese in meaning
- [ ] #188: Use ン instead of ん for on'yomi

**Comment by davidsansome** [comment]
Hey!
Is this a personal checklist of things you want to work on?
I'm wondering what (if anything) I should do with it :smile:

**Comment by turtlemaster19** [comment]
No, it's just a place to show what needs to be done with reviews, since there's been several issues with reviews that have been opened within a ~2 week period. I'll check them off if I see that a PR solved them, and that issue is closed. **Feel free to close it if it's distracting you, or you think it would be more beneficial if closed.**

P.S. I wish I was able to work on this, but I don't know where to start learning Swift and Xcode's interface. The official book on Swift is kind of long, and I have no clue what to do with Xcode. I do have it installed, so I was able to submit the pull request that enabled Mac support.

**Comment by davidsansome** [comment]
Ah I see!  How about if we use Github labels instead, and assign a "Reviews" label to each of those issues.  I'd prefer that kind of grouping over opening other checklist bugs.

As for learning Swift and Xcode I'd highlight recommend the Big Nerd Ranch guide (https://www.bignerdranch.com/books/ios-programming-the-big-nerd-ranch-guide-sixth-edition/) - the first few chapters will get you started with Xcode and the basics of app development, and then the later chapters dig deeper into specific topics.

**Comment by turtlemaster19** [comment]
This issue will remain closed unless someone else re-opens it because there are more important problems to address.

**Comment by turtlemaster19** [comment]
@davidsansome Can you close some of the duplicates? We can keep the main issues open, but having all the dupes open makes it harder to keep track of the real issues.

**Comment by turtlemaster19** [comment]
@davidsansome Would you mind reviewing this again?

---

P.S. If you are the author of any of the solved issues and you object to it being on this list, please let me know.

If you agree, please close the issue so that we can focus on the actual issues that need to be taken care of.
