### ISSUE TITLE
Dark mode checklist

### ISSUE THREAD

**Issue by indirect** [davidsansome/tsurukame#216]
Here's a running list of dark/light mode things I've noticed that could be improved. I plan to work through them as I have time, but anyone should free to tackle any of these and open a PR.

Needs a fix in dark mode:
- [x] remaining time (eg 3d 4h) should be light
- [x] "burned" label on dashboard should be light/readable
- [x] review answer field text should be visible as it is typed
- [x] lesson hint text should be dark background, light text
- [x] chart labels text are black but should be white
- [x] multiline strings right hand margin color should not be visible
- [x] hint text on e.g. kanji mnemonics should update to secondary text color
- [x] lessons chip holder should be dark background
- [x] highlight colors should be dark wanikani colors, with white text
- [x] download audio list should be dark background, light text
- [x] font chooser screenshots should be dark background, light text

Needs a fix in light mode:
- [x] NSAttributedString should not have visible backgrounds
- [x] text in Review mode description, above the answer text field

**Comment by turtlemaster19** [comment]
Great! Just referencing #97 in case anyone is following along there

**Comment by indirect** [comment]
Once #229 is merged, the remaining three will be harder:

Highlight colors are NSAttributedStrings set to hard-coded colors, and don't (currently) update when dark mode activates. My theory for how to fix this is to switch to using Asset colors, which have the ability to include dark mode variants. That might mean requiring iOS 10+.

The download audio seems easier but more tedious, updating every color used in those views.

The font screenshots is probably the hardest, since the FontScreenshotter doesn't even build right now. Someday, maybe.

**Comment by mzsanford** [comment]
I think I have an easy fix for the highlight issue, PR upcoming.

**Comment by davidsansome** [comment]
I've done most of these now!  There's one final one I want to fix: the "Meaning" / "Reading" bar above the answer field on the review VC is a bit bright.

**Comment by turtlemaster19** [comment]
> That might mean requiring iOS 10+.

We already do.
