### ISSUE TITLE
Support WaniKani Image Mnemonics for subject artwork [meta-feature]

### ISSUE THREAD

**Issue by aaron-meyers** [davidsansome/tsurukame#689]
I would like to see Tsurukame support artwork from the [WaniKani Image Mnemonics community project](https://community.wanikani.com/t/new-volunteer-project-were-using-ai-to-create-mnemonic-images-for-every-radical-kanji-vocabulary-come-join-us/58234). This is a meta-feature comprising several sub-features as mentioned originally in #653.

Individual features (in priority order):

- [ ] Switch to WaniKani Image Mnemonics project for subject artwork
- [ ] Offline support for subject image artwork
- [ ] Support custom URLs for subject image artwork
- [ ] Support multiple custom subject images

TODO - will add links to the individual features after I create them
